version: '3.4'

x-var:
  &APP_NAME ${CONTAINER_NAME:-backend}

services:
  backend:
    container_name: *APP_NAME
    image: *APP_NAME
    build: .
    restart: always
    ports:
      - ${EXTERNAL_PORT:-5001}:${DOCKER_PORT:-80}
    networks:
      - rip-network

networks:
  rip-network:
    external: true
