version: '3.4'

x-var:
  &APP_NAME ${CONTAINER_NAME:-static-server}

services:
  static-server:
    container_name: *APP_NAME
    image: nginx:alpine
    restart: always
    ports:
      - ${EXTERNAL_PORT:-5002}:${DOCKER_PORT:-80}
    volumes:
      - ./static/:/usr/share/www/html
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - rip-network

networks:
  rip-network:
    external: true
